---
master_ip: 192.168.77.2
# the client IP will not be used in the end (undercloud will assign one),
# but Vagrant expects it to be present anyway
clients:
  - ip: 192.168.77.101
    mac: '52:54:00:11:11:01'
  - ip: 192.168.77.102
    mac: '52:54:00:11:11:02'
  - ip: 192.168.77.103
    mac: '52:54:00:11:11:03'
  - ip: 192.168.77.104
    mac: '52:54:00:11:11:04'
dns_domain: instack.dev
aws:
  ami: <AMI>
  ami_region: <AMI_REGION>
  ssh_user: <SSH_USER>
libvirt:
  default_network: instack_default
  default_prefix: instack
  storage_pool_name: vagrant
  private_net_0: instack_77
  box: rhel-7.0
  box_url: file:///home/jistr/projects/vagrant-libvirt-image-tools/output/rhel-7.0.box
  ironic_ssh_user: stack
  ironic_ssh_ip: 192.168.77.1
  ironic_ssh_private_key: ironic-keys/id_rsa
